name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: python_unittest
        run: |
          sudo apt update
          sudo apt install python3
          python3 --version
          pip3 install -r requirements.txt
          cd /home/runner/work/stock_price_prediction/stock_price_prediction
          coverage run -m unittest discover
          coverage report
