name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build Docker image
        run: |
          docker build --no-cache -t unittest .

      - name: Run tests inside Docker container and Unittest
        run: |
          docker run --rm -v ${{ github.workspace }}:/stock_price_prediction --name unittest unittest /bin/bash -c "\
            cd /stock_price_prediction && \
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env && \
            echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env && \
            echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env && \
            echo "DATABASE_PATH=${{ secrets.DATABASE_PATH }}" >> .env && \
            echo "TEST_CREATE_PATH=${{ secrets.TEST_CREATE_PATH }}" >> .env && \
            echo "TEST_DELETE_PATH=${{ secrets.TEST_DELETE_PATH }}" >> .env && \
            echo "TEST_DATABASE_PATH=${{ secrets.TEST_DATABASE_PATH }}" >> .env && \
            echo "CUDA_VISIBLE_DEVICES=${{ secrets.CUDA_VISIBLE_DEVICES }}" >> .env && \
            pip install pipenv && \
            pipenv install -r requirements.txt && \
            pipenv run pip list && \
            pipenv run coverage run -m unittest discover && \
            pipenv run coverage report"
