name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build Docker image
        run: |
          docker build -t unittest .

      - name: Run tests inside Docker container and Unittest
        run: |
          docker container run -v ${{ github.workspace }}:/stock_price_prediction --name unittest unittest
          docker exec unittest ls -la /stock_price_prediction
          docker exec unittest pip3 install -r /stock_price_prediction/requirements.txt
          docker exec unittest python3 -m unittest discover /stock_price_prediction
          docker exec unittest coverage run -m unittest discover /stock_price_prediction
          docker exec unittest coverage report
