name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build Docker image
        run: |
          docker build -t myworkspace .

      - name: Run tests inside Docker container and Unittest
        run: |
          docker container run -it -v ${{ github.workspace }}:/workspace
          ls -la
          cd ./workspace
          ls -la
          python -m unittest discover
          coverage run -m unittest discover
          coverage report"
