name: UnitTest

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build Docker image
        run: |
          docker build -t unittest .

      - name: Run tests inside Docker container and Unittest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/stock_price_prediction --name unittest -e CUDA_VISIBLE_DEVICES=-1 unittest /bin/bash -c "\
            echo 'Inside container, CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES && \
            cd /stock_price_prediction && \
            pip install pipenv && \
            pipenv install --deploy --ignore-pipfile && \
            pipenv run pip list && \
            pipenv run coverage run -m unittest discover && \
            pipenv run coverage report"
